### ISSUE TITLE
Why all these boot arguments?

### ISSUE THREAD

**Issue by thirstyraven** [mojo2012/hackintosh-stuff#1]
You add the boot arguments for WhateverGreen like this:

```bash
# master branch
$ sudo nvram boot-args="kext-dev-mode=1 -cdfon -enable-hdmi20 -cdfbeta"
# MacBookPro12,1 branch
$ sudo nvram boot-args="kext-dev-mode=1 -cdfon -enable-hdmi20 -cdfbeta -igdvmtbeta -igdmvtdbg -cdfdbg -igfxdbg -igfxmlr enable-dpcd-max-link-rate-fix enable-hdmi-dividers-fix"
```

Based on my research:
* `kext-dev-mode` ships with macOS, it's used to allow unsigned Kernel Extensions
* `-cdfon` and `-igfxmlr` are boot arguments that ship with WhateverGreen, and `enable-hdmi20`, `enable-dpcd-max-link-rate-fix`, and `enable-hdmi-dividers-fix` are _properties_ (for the Clover EFI bootloader's configuration?)

As per [WhateverGreen's documentation](https://github.com/acidanthera/WhateverGreen#boot-arguments):
> -cdfon (and enable-hdmi20 property) to enable HDMI 2.0 patches.
> -igfxmlr boot argument (and enable-dpcd-max-link-rate-fix property) to apply the maximum link rate fix.
> -igfxhdmidivs boot argument (and enable-hdmi-dividers-fix property) to fix the infinite loop on establishing Intel HDMI connections with a higher pixel clock rate on SKL, KBL and CFL platforms.

* I can't find any references to the 5 remaining arguments `-cdfbeta`, `-igdvmtbeta`, `-igdmvtdbg`, `-cdfdbg`, or `-igfxdbg`

My questions to you are:
1. What do the 5 remaining arguments do, where do they come from, and are they still relevant?
2. Without Clover, how do I add the property as asked by WhateverGreen? I see you adding them directly to the boot-args NVRAM variable, however `enable-hdmi20` is prefixed with a hyphen whereas `enable-dpcd-max-link-rate-fix` and `enable-hdmi-dividers-fix` aren't, so I'm a bit confused. How come only one of them is prefixed with a hyphen, shouldn't it be consistent across all of them?
3. Is the MacBookPro12,1 branch meant for the 2017 12" model and the master branch for all other models? I have a MacBook 13" late 2016 model, and neither of these branches worked for me.

**Comment by mojo2012** [comment]
Hey there,

I think I found them here: https://www.hackintosh-forum.de/forum/thread/32411-lilu-plugins-mit-bootflags-und-beispielen/
It very well be that those are not supported anymore - but as I was experimenting a lot to get everything properly working I didn't dare experimenting any further :-D

Unfortunately whatevergreen is not consistent :-/. Look at the github readme: https://github.com/acidanthera/WhateverGreen

The repo is actually for my hackintosh (intel dh77df mainboard + core i7). The macbook branch is for my 13" macbook early 2015. I think.

Have you tried https://9to5mac.com/2016/06/04/how-to-enable-4k-60hz-resolution-2016-macbook/. That looks like it might help you if you want 4k@60Hz.

**Comment by thirstyraven** [comment]
> Have you tried https://9to5mac.com/2016/06/04/how-to-enable-4k-60hz-resolution-2016-macbook/. That looks like it might help you if you want 4k@60Hz.

It takes me to https://github.com/Floris497/mac-pixel-clock-patch-V2 , which doesn't work for me for the latest macOS version. I've [filed an issue](https://github.com/Floris497/mac-pixel-clock-patch-V2/issues/353) and the repo owner is helping me.

Thanks!
